"""
output/markdown_report.py — Writes YYYY-MM-DD_leakage_report.md.
"""
import os
import json
from datetime import datetime, timezone
from pathlib import Path
from config import OUTPUT_DIR
from analysis.dollar_quantifier import LeakageSummary


def write_report(summary: LeakageSummary, ai_result: dict, flags: list) -> str:
    """Write the full leakage report to markdown. Returns the file path."""
    Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    path = os.path.join(OUTPUT_DIR, f"{date_str}_leakage_report.md")

    exec_summary = ai_result.get("executive_summary", "Analysis unavailable.")
    score = ai_result.get("pipeline_score", "N/A")
    bottleneck = ai_result.get("bottleneck_narrative", "")
    actions = ai_result.get("top_actions", [])

    lines = [
        f"# Revenue Leakage Report — {date_str}",
        f"*Generated by Revenue Leakage Diagnostic | myAutoBots.AI — Sammy Samet*",
        "",
        "## Executive Summary",
        "",
        exec_summary,
        "",
        f"> **Pipeline Health Score: {score}/100**",
        f"> {bottleneck}",
        "",
        "## Leakage Summary",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Total pipeline scanned | ${summary.total_pipeline_value:,.0f} |",
        f"| **Estimated revenue at risk** | **${summary.total_estimated_leakage:,.0f}** |",
        f"| Leakage % | {summary.leakage_pct:.1f}% |",
        f"| Deals flagged | {summary.deals_flagged} of {summary.total_deals} |",
        f"| Critical | {summary.critical_count} | High | {summary.high_count} | Medium | {summary.medium_count} |",
        "",
        "## Priority Actions",
        "",
    ]

    for a in actions:
        lines.append(f"{a['priority']}. **{a['action']}** — *{a['estimated_recovery']} estimated recovery*")
    lines.append("")

    lines += [
        "## Top Leakage Signals",
        "",
        "| Severity | Deal | Stage | Signal | Est. Loss | Recommendation |",
        "|---|---|---|---|---|---|",
    ]
    for flag in summary.top_flags:
        est = f"${flag.estimated_loss:,.0f}" if flag.estimated_loss else "—"
        lines.append(
            f"| **{flag.severity.upper()}** | {flag.deal_name} | {flag.stage_label} | {flag.signal} | {est} | {flag.recommendation} |"
        )

    lines += [
        "",
        "## Leakage by Stage",
        "",
        "| Stage | Estimated Loss |",
        "|---|---|",
    ]
    for stage, loss in sorted(summary.by_stage.items(), key=lambda x: x[1], reverse=True):
        lines.append(f"| {stage} | ${loss:,.0f} |")

    lines += [
        "",
        "---",
        "",
        "## Methodology",
        "",
        "Loss weights are probability-based estimates derived from industry benchmarks:",
        "- **No Next Step**: 42% loss weight (HubSpot Pipeline Benchmark Report 2024)",
        "- **Stuck Deal**: 35% loss weight (Salesforce State of Sales Report 2024)",
        "- **No Activity**: 28% loss weight (Gong Revenue Intelligence 2024)",
        "- **Deal Velocity**: 22% loss weight (Salesforce benchmark data)",
        "- **Missing Enrichment**: 18% loss weight (Apollo.io data quality study)",
        "",
        "Deduplication: deals flagged by multiple scorers use the single highest loss estimate.",
        "",
        "---",
        "",
        "*This report was generated as part of Phase 1 of the Neural-GTM Sprint.*",
        "*Full engagement: Revenue Architecture Audit — $5,000–$7,500 fixed scope.*",
        "*[Book a free 30-min discovery call](https://calendly.com/ssam8005/30min) | [myAutoBots.AI](https://myautobots.ai)*",
    ]

    with open(path, "w") as f:
        f.write("
".join(lines))

    return path
